services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_EXTERNAL_PORT:-80}:${FRONTEND_PORT:-80}"
    depends_on:
      - backend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-80}
    volumes:
      - ./frontend/pages:/usr/share/nginx/html/pages
    networks:
      - c20-network

  backend:
    build: ./backend
    ports:
      - "${BACKEND_EXTERNAL_PORT:-5000}:${BACKEND_PORT:-5000}"
    environment:
      - FLASK_ENV=production
      - BACKEND_PORT=${BACKEND_PORT:-5000}
      - HARDWARE_MODE=${HARDWARE_MODE:-mock}
      - DEVICE_NAME=${DEVICE_NAME:-CONNECT 500}
      - DEVICE_TYPE=${DEVICE_TYPE:-C20}
      - IP_HOST=${IP_HOST:-192.168.1.10}
      - SERIAL_PORT=${SERIAL_PORT:-/dev/ttyUSB0}
      - SERIAL_BAUD=${SERIAL_BAUD:-9600}
    volumes:
      - ./backend/menu.yaml:/app/menu.yaml
    networks:
      - c20-network

  nodejs-api:
    build: ./nodejs-api
    ports:
      - "${NODEJS_API_EXTERNAL_PORT:-3001}:${NODEJS_API_PORT:-3001}"
    environment:
      - PORT=${NODEJS_API_PORT:-3001}
    depends_on:
      - backend
    networks:
      - c20-network

networks:
  c20-network:
    driver: bridge
