version: "3.8"
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
